ansible_become_pass: ENC[AES256_GCM,data:z156WmPoIdS26Mxc,iv:x93RJ0nuZ5h+VGXjS/NRqydiu8CTy2Csb3dZMqNR+ng=,tag:nr5viYSVNVoX6T9BRNl6JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UldGL1dYOTQzdWsrempx
            UlA5cFNOR1c1c3NBMmpNZDZxSjg0c3FNR1dzCmE2aFg2Vnh0WHc2N3hHbExVb3Jn
            dEx5RjMweU9XM1p1UUUyMlNJTlNvdUEKLS0tIER6bC9YSHc2UUdnbm1xaHcwNnhO
            S3NUdU41ZnNhamlQVzNjd0x6NWc3aEUK7aLGVWBX4plAtqRJvgst4Rt59NLHmjwi
            hRPfkONJRJbmZ4PSwX3OZNgzlnD8cLExrhLlRW+a/CMAm3z7ijN6Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T16:12:33Z"
    mac: ENC[AES256_GCM,data:NO6nlx3gfFMNjE6FaRwnWC86hqinTo78sU56uvBo5v/6ZDoy/nJouUdH3mIA8F727K6pgq1FsNdLdcBfbjkcG8GLB/573jq40itkRUD9Xsq8Kn6+2+E1SyWQrA3x+40LNL/U9gCDVI3gAk00vRc/Ug9+0J4muEJpT7hBhYTrGqs=,iv:4H8wKrv2vTqHvYA+5Ir5B7zqxIZ0tHvCi4H4vThTgOQ=,tag:Yyd2Z66un7WWGxElolst1w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
