ansible_become_pass: ENC[AES256_GCM,data:aFrTm6vVYrBjaAZS,iv:XdwvK1pYIPBHWV5QvjWdyyoa1FKaW5t9cF+9iHcyrZY=,tag:xtsudVHWwdh47I9BKRGE1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcncrUDdQZG10dmsyeFl3
            ODk1VVk2YklzMVlkVS9iZ3lxMXBWK0dnYVR3CjFzK0M1S3NXQ3pDWkxyam44Mlgr
            SlZXM3NtUnp2YXFmOHNJVW5iN0lOMFEKLS0tIFY0V2VRcENkUlg5YTVEME9xcVkv
            bmtDVGNZcTd0RGZyT00rQU5yWGNDc0kKouGWWVQDryaYcCVmL85rhhU0GZEj3SZC
            SrnpRGehGd2bA4RdJ/o3ZRbGZmjLOsKevItB0KjpBkTeltAOMG5u/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T14:26:17Z"
    mac: ENC[AES256_GCM,data:AzL1p6iXiaAGlWp1XAkSkBwUU9+9fFCGbJCamVIJLJ+2DnP+PymN9qJGQn+CVRSjy98/Kx8Z5MtzAMB8e92u4axvuyFVefihCUI6l0WUwP9ybmT/rUAzkzHvUgTufU5+1BEc1PuP/iRcNZ8SjjbtQZNxgy82d0247EAtqWBaY5U=,iv:KM2+hZL5N525G+3CSl8Onm9iItW3rno1WEjOfxtvEKQ=,tag:xV3EDqCbsCLYukzWB9jorQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
