ansible_become_pass: ENC[AES256_GCM,data:agrNTqlBUG0SWQU3,iv:/AIG3Fz9j1szw/23NB8OWQ9V99vhILC/DcEyHtYOnpE=,tag:OMHmWJCqLenpoNjfTIg9Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUFYyVTMzd3FCK1gzYURX
            TmUvWjJyMXU1Ym5Uc3NLUFkwY0FidEg4MnhZCkNTNG9LajdheXF3WUxlaG9kTmZX
            UjdBOUsxOGNiTTVKblhPV0M1c3B4OVEKLS0tIG0xcjRtRktPZGlpVXd0SE5ObjdK
            aXNXSDFpYUR0UGFrVWpsNHZLR2FnZTgKWA7KKR4NjCyQGm6vImtaOwRXmf/pPA8+
            C8xKxiEoxsXbNr9caQAEEAuQGEr5e1GZ8uZSfwsZNcfJp4SlnBNP/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T16:18:25Z"
    mac: ENC[AES256_GCM,data:Dby5VXHkFPWtFnCquD/8MnUcbhLkkioGYkbTnJ2dJEtTo1oz7nRaoFkfmJpwA+qEevJ/5MUHxs0IZ118+vgSxuon6oFN+OI2JE/kwnCYQrJWS4aFHQgF7s9R+IDXOe3uCETcIqw0N5RRPw6vWj4lzH63RQRAcy6JLiqKOFyab4Y=,iv:yFrPz8LYutQ6G4Esh9t7YphdNx6343f+ganZNYSM2jI=,tag:pMcMmEiyDKIfeGLnqXi3RQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
