ansible_become_pass: ENC[AES256_GCM,data:fvTOgEn3Hch7EFQD,iv:fUBEdoIBxXxWxmQsInxyZkeXjw9BlRdRdVACt7COanI=,tag:Br2fzTVf5YX6tPsN2s9GUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdENLbmNpaDkyK1pOMG5j
            TjloelpXSUVMcDVJUWlWZ2E2V3lOcjJ0UGlRCmtNT3g4YmFvLzY3am5aU01wZGJp
            RVFXNEZDS2JsWG8yK1JQZ0xFb3JnK1UKLS0tIGQ2ODhzMlprNDRxa0RKbncwMldx
            ZDVrYnBlTzZ0QjlHWktYRHBtdGkydVkKSOr/O3WPo8jtboJYJd36VMa+Ipc+1byZ
            e9ehQOaFff90pdgcAzlXz8nkUrsdITLjhzxKrxpuc666CgVxZWcPow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T05:32:12Z"
    mac: ENC[AES256_GCM,data:grKEYNm7bE0oKzlfSOp3c1eYOmhwhm+Z8Mf8d4OD3sm445wADjxBA/WIBIb5ATbMuyVWnSSrwwnyHAzitKDo+YH3tfe5E2MA2764jylYS9b0VeF1NMGA2HN6sAXsxIHOx/KH9FYViFmMWxdlmd+qs7Hs3bSq0idxhWIG4Jqaap0=,iv:JtiCsE9rXHw1Ze9Y9OZlw5krzXqr1UuGHuqEi457iwU=,tag:2YxBtpK5JhMn/2h9XfMGtw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
