ansible_become_pass: ENC[AES256_GCM,data:6nnQiD0PHpGO40x2,iv:bQkGczrrNdmp60lJ/mL8ztzcED5Ki0zq5H6SIcuvgVw=,tag:d4oM2J8pXFeL49mDWgciDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR3U5VWw5em5RUFNPcXpQ
            cytheml2b2lDaVdiU2VBdkIwQ1ZoSnFqaUJRCkNndjg2R0tPaExMWWoxSnBiTzBM
            VngwOWZjbDAzNzNnaHp3ZFEyd3pYNVEKLS0tIG5ZSEEyTkZ3N21IdDhYZkVMSzBJ
            NDlvODJQcUJERXNVMDdsVHM4ZXZwVHMKOrAa/QmKxPzMrZcgPeJgUwSgLMGRIMkw
            9i7wQ02ecdpErBZ5EN7j4OcBVXEYiRkReOhV/ugAJJx763FHETbVtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T14:35:40Z"
    mac: ENC[AES256_GCM,data:obAueh5k6r0MCxssDew9qutKHzu0rOMe2BV9wtBnWqbp/eauYmpAWSPEHkrBcQux8dxj5fMZGUH1z3Yfr6nKzu9qvsWWCoNMPGkC8MSFCFAFnFiQV/u7juoY3jZHjiQ+kHffTEJMhSkuv0JBGEfB9DFDaeml1LTwJK2XaE+Uuiw=,iv:WlrfCn2I7pVwn70Cm5kE4TCEu9Pt/GNjJ0rzsIuIda4=,tag:h6VJZpqVXyA2v9OB3eSyHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
