ansible_become_pass: ENC[AES256_GCM,data:hxBS6HdtbJM4cMsa,iv:tNPCzPa63GFJWpmy89Wc2iFAjcbo72syxw+NypBLnvA=,tag:r738hQEPFW6B7hDtsHUpPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZDZjOXlWSlZFWjlydnJl
            SGZjR1dCSit0MTc4dHRoVVV1d3h1ZlRIeDB3CjJqbEZCbDFYYTkvd0I4blJHNzJD
            d3VHYlo4NGJjaUQvREZ0ZGVINUZoakEKLS0tIFpkWmtCUm5vNTNlWjc5Ung4ZnRU
            UDN6N1lBa1JYQWxMbHViNG9GT0g5YncKGa6TURVpoKoHGRGSBDYI3y6GhKJ+1qMS
            vTHA9cUuBwpDys5gkzm5F+1LsLm5KdF0MEA2fcuk2U7OV2bBxY33ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:35:46Z"
    mac: ENC[AES256_GCM,data:OCNIuN4YtecDbAMJ4ckUv6u/vQep3AawUGwnuMiUz/MubtmdJow/7F9TWR7WPq/YwXwqzzOs6ainxuKXFW2GcPB1qB0sXQcoZi5Dcu/uLYXly8FMFw5XRXyCJpdFOZT1gwSihECltbvDdNWhOFfpPfIA3PrAzC39h5wQgTZ0kMQ=,iv:Yl+S0SZSwsr9urJMpQNlMPCMJAbREFzBQwTaFT8HWS4=,tag:6JliiMwxGdhbIPDKnc0gbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
