ansible_become_pass: ENC[AES256_GCM,data:VI75WcUrxu1UReJg,iv:yfuzQhrdOtia45ogE4U8n44DS0cMA8GAEfuvxbmmv4M=,tag:tBrIr+dDp73ALTgfAs5Uyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSDRmbXpNNmEwY05OaTh5
            UzNOL0MvNURhWWRzSEtya3ZKRTFJSmJLdXpRClZnbFdGaDRGK3NwczZSV2ptcjBN
            ZUpGeUhoTXh5M09sR0FWSG84VzdxY2sKLS0tIGRsYlkvSHo3Q2dnOFVzRTNKQ0xq
            czRld2JGekZFWDFKUmVONExrQldHdWMKYPEb3RQROs7Tif9jnnVQjq4kbCVs73jR
            eHQFX3+fJDivunvnAdJLM7sHjRD70y6Jc3homSjhUyBwNuimKFKAJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T04:49:26Z"
    mac: ENC[AES256_GCM,data:/SFoqFhc7ZoZKEFr0b4odwRkH2ggOtrMjbYrUmyPFx9vn3qA5dSPkAzK7EcZfhGWCmkUH2juPrMNdvKfFtjrrUh3d118GLZ+wzGQIAIXEtDediWcqfJpRnP1wFXE09Dzxk4q6x5gEEFbhYE95s7kKAlUSfl86DnvrM5gdQ5tHhM=,iv:p6PZEcHuFD6/68iDcnZK5TAO76edAV1HPgnKc/BrtR4=,tag:fIKrh6gzF1ssVxMjey7kig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
