ansible_become_pass: ENC[AES256_GCM,data:mnbqb8wkJSF0ShYr,iv:40HDvYfUMnxb/58oyVV9zGPZZVzItYyh9SiB39+N6/I=,tag:lw6y2V3xml7YIsbON2ZYjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQk9aZkhaYW5mVUt6VGMx
            d2dNeGMzdE84Y1Y3MUVvb1hrNi9RVUQ0akhzCkd0WVNzWEhyQXBHN2NOUnNBYkpQ
            YUhwTHJPS2U0YWROSTNheXF6MDgzdnMKLS0tIDFNcUhvT0Rnb2FIZUJ4aU5ZS2RT
            eG05TDN1alZSVjNpVGp2STJiZWM2alEKpPDa111ptgTPH+X8kGeFHRXe7VnHzJTt
            tN6FMdhuBhNKbfPjIrBR+4GXLOjg/bthTTDrgBUSHB0hlPsl8gW1ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-15T01:07:05Z"
    mac: ENC[AES256_GCM,data:zC9YrOGd3FyFm1MWrpKuTBdpifZq2gP4lbdSWD3FqAAQ5QdNmQ7v5wcuhbdkwxsJKJ2uNqJtxTrz5qDELoZfFXpYshKBbfrWDA2oYDdePKWtdMupo3ThNrRhuuCbvMY/b1Qon4rQ5UangsLaiKDXNW+57BClDbqduSdMrNN05j0=,iv:NO7uvjg+kQZCAPw9M+mK/Si5PNMOWV952PgUBa+cP6s=,tag:TIOkYiZg3lMRP2DOZBMzJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
