ansible_become_pass: ENC[AES256_GCM,data:Isr/lBYQptBMwM5a,iv:IfYKP/4Q9SQUueW8OvXm0l8vAlPFxKFi6OPJxacCh6k=,tag:BLtUtpBndSKrfh6d4jWqbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveHBOaktDUEZjSXE1NGho
            d1o2L0JkSE55NGFiNGxPakJZT2p0OEk3LzJNClFjTHNjdzBQQU1oWTJSeFQ2RlZK
            N3hxdkc3TzE1VjZEZHFPM3Q5VTRwaEEKLS0tIGZFSFRMS0pQc2ptdUdhUnJDdlBK
            L2kvZHhaU2gxRjE2Yy9YOWc2L09YdmMKQuE65q8oxd+v0UeMl3hNPzAs0wmEC6on
            q97szxOU50N1NrDKEXqw4dx2P10ekN37TSFq1oHsywXtf1xTv3a02w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T03:46:12Z"
    mac: ENC[AES256_GCM,data:TtbZtx6acz8JhetiCPJ7RFFmeqJNvOfUUlaFIhaXp1c6GAo1gI4H3znXS7udq4M/UjSVsACTaCLJMqe9nrVlDpzK4sp1BW3ZR0densDyelylXeskRUO1AFBbOboWMgd9MRMOqWWxGkT2n0U+CaR4Pce3CzCT4zMrw+HM5yH82Ck=,iv:EEB7hRiI4FJDiyJZzJnG+aByJ88mpQED8ZhNwzBGWhI=,tag:vhsuTb2tjOiWW9fBsdC0FA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
