ansible_become_pass: ENC[AES256_GCM,data:zIQ3j4wyzURdoJN1,iv:HvknzInJGyoo4iLWuq8gHKmApXR5eFXGsTFf9UtcMPg=,tag:4PgKZURC1o3W0Z3d9OZo8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUlwMVovWmxJdnpONmZT
            NE9ZMDl5cTVzR1hYUlhIOVFsa1EwN1hINGtJCmlyd2JHTFpzNjEvU2NBZEpGdmtH
            SE0vNm5FdWRBWUIrNVB6Ym5ocmh0cmsKLS0tIHVWMy9maUR4eFd2MHJlUjZQYW5V
            bExGRjZlSEg1dHVScTA2RFM2elBpN1EKRkSfF+Mg301C1TyyhoPhuNzDyMtUIe73
            xaVKGHpijnxukD9Cjla5/TrQPV7loougrrnRs2NW2bIZmAo9MRB1Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T04:49:26Z"
    mac: ENC[AES256_GCM,data:fAuBpSwEvcOIVtoPITnp4e1tRZpohkHMjYmfto5NsUKk4pzhmywaGC8gV1otNXFeMPa0T20ALtZVRK8DiaGHgXpNa+dqLp/a/uynUwV4o2qtyomJpnUS6tjY5hKIKADqpvn49CQLFcEZ255pWlGuoozSZXPtiuCUMOQ0Z4rwnXQ=,iv:AvNe+z+/N039Xgn7tzswAO75Ep2IxTzeevUZDE72BzY=,tag:zrw3Kr6TpnaKorl/TmaVZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
