ansible_become_pass: ENC[AES256_GCM,data:l7WV2FxkY42u+7dm,iv:MNDXLfBalZ1fz00zEkBGEdYLilFqdiPgnihP2AxAgoM=,tag:e8CMc9jCS5qbVWkjz4kDDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaWdJUFdoa1I3ZW90Rm9w
            VHoydStzNVlRa1hUNHpjTUt3NWtNVVJEVlhJCkdjWG1YY0xjNnNNcUVramhHcDdn
            SGtWdEdwV1ZWdHBSUDlUK3I3OWhRelEKLS0tIGZDVzIwYnk5bC90Z0Jrc3VEQTg2
            S2RoUUZkZ0NhdkVmeXJRQW5jamhselEKwU5rAdNg17uubRgSvlkZYZXveDE+HtA/
            KCPb7b81jLl0uulO+KJTK6joSBLm/75OBaCDjsH9JUQjtVH8T/NWsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T16:18:25Z"
    mac: ENC[AES256_GCM,data:L94WurJsYTac9+ggW93PGZ0St/6o/95H6Ji2438U0bqkpuA6N5EeHR7pGBwpCGgWjgOT8SMPvEqcOPO9hZjMTVvZWTjJHwV4fkVdbkb5/3fKKNno/jJinCaw0iF4j8wpKvbYOuAzrDTmwwJ2gTBHR35v/awiO7L+rjpegyI66Kk=,iv:1B8Xv2ylfTP9AGM5CG9dF/A+CdFruJHbXYkuquo+E6g=,tag:2mft350qTKcJ070bcf7mfw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
