ansible_become_pass: ENC[AES256_GCM,data:E1LEovzmsG+XNVoU,iv:Qx6w0jN7+2Rjzo9T7pa5l78RLcPR0pd9e5qmiMrpgwQ=,tag:I+JWgyGZVWiR9IOgA4sbGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bWhwOEhDU2NPYWFKREZ6
            cm5GUFVWSVRYVUZZRDdJVjJlMVZROWZMSGhBCm1kVU10VTVaY3hTT3dNQ3lGZm05
            SHFscEdHcU1pc0M0MjMxV3pUYkJYb0kKLS0tIFJTTGtsb09lMFNJU2lBenpZTUZ1
            K3hySnVkNGFlT0svS3MxdDVKZWZtYTQKDDUSZezkA46gt+gPFG7CwhD3Hq2BqmDl
            t7U6vxpItO/DC6rUYvGjby0lGGux1DF3HyHwcEUdoCvk4W+5/hIC6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:17:49Z"
    mac: ENC[AES256_GCM,data:K2cBGUVeW7B6S7tw5bI0ydPKP/JBJejPunaKii3zTyvTFz4ie7PKr+LDIKGr2OvS/pwVuaa5NlNY6gaUMiZ4ORidcExKyyeVuOEbsNAbznbkPZzY6g15GBH0xcHJM0V+nwfDDqf9SUGylH7cKLEja5W1cvL6NgIjg1D1ncjmVnc=,iv:0aopqclh+4w4WDYlKbZfyk2LiOscveJG7jEAAujnazY=,tag:kdyeytZAVO7o57BED/Di+g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
