ansible_become_pass: ENC[AES256_GCM,data:oIiD0Ee9ZNl4dHBd,iv:zJxREcA8OPmjA62+D6gPm7wTxGbKzwJoIKGAZzGBuos=,tag:A410aKc0o0UkAR6CuHRknQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYklpSEVsaHdJRGNVOUlN
            U2FVZVEwYUI2eGlyTGpTRlRIalR6dUw1U2wwCnczV21BY3NDK1RUQkxhYzdZOER6
            a1VaOG55YVpXTHJNdVRoanFIQlZ0L3cKLS0tIFRwTXZ4UEtKOGpKYkF1TS9hdDJv
            K3ZoM0ZwWW54elBHOUV6QmxnamdHMlkKpltm+F79WLWb96rktACeV91ziyCFmukq
            SOi9FKtxkdA5ImdkU28ibTEbXgbDV3t3jc/LfqDjlr786BxvJ8PUlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:35:46Z"
    mac: ENC[AES256_GCM,data:CD0okDmK5O56SdCmZmIW56hqFiI340aV93c14gGfARzqKKRlXOOWapBU7Q5ZIr1zmf6ONuEd2C284Qg8BlIxf0aU63brdYNp4ZPOEDBxuuuW0TOlNxozsiQe9gyWYcukWsu8Uqik8dfyBc1BUkpnTHjMp5tGzVECaRp8C1qDexg=,iv:AAKLfhb8vebchkubO83v8GZUd9dlzurLgb6saR5KRks=,tag:q1T78GxNkxH3qihBeqTKxA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
