ansible_become_pass: ENC[AES256_GCM,data:CVWTm3ZElUCQXUm1,iv:ZJTz0AA9v+ELh8zYQAYN9Tt0kSSPddKVYpUvCA0ZhVc=,tag:/ajPLj0Nfmq3uDvtRtkB/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUkRJNjI0eDduNmhXc2lC
            WHIxL0tZSGp6U3NLbG1hRHlGQkVUTkpGM1FZCnFRbGorM0w4Nm8yVFFESDBZNk1X
            WmxaaTFhd3hYSnFlWk5ENk84WU15cW8KLS0tIHZZQlpVNWxXWk8vWnQ4STd5c04v
            K0lZM25WRG8yVlc2N0wwdm5ibU1CYzAKZhcFKT+NxdHuOuHhi4ByK1HOWgtt612Q
            Xc3cGK1/y4BzIQF5iAsdH19JSfwW84t/AAhrK+ZqhR4CqH2UbUqLog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T13:13:45Z"
    mac: ENC[AES256_GCM,data:cgnkxNWDklj6lQmgLhZX3ID0GIH/aZWcdp5jjLZwRdEm0zzbpe96niSoFjkyALEv4Rope/rh3KgGJgJ/+U9jh/pz1tgOwOSnLsPCAbDF9ept6/maTBy09EZR4EphH5IlleJHcDUv+fe0A/LD/ONDg99ZwOj2uCUNZrnx5kdBxPs=,iv:2KGA7MxOsjX2p1Y9ZxaHqduyahaxWzqDaY/Qnx/cZA8=,tag:kbaXajMfQZEcPaC9YBIyiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
