ansible_become_pass: ENC[AES256_GCM,data:BLDqliXVQSvIgBNa,iv:LfxYltmEzp5HuUEZ2uHwpwfP1V8eNIRQj+Q+ZMt2SHQ=,tag:Wv/2dEzwawWWnhniWOnImA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc3ppendBZ2huSisyN21h
            Z05SQlpvczByOUw1NVlPOGVvWDBDMnZEdVR3CnhDKzhhb2xyeEtqRzVRL1E4dENN
            MjR4NTlVK25IZjZTbHI1bXAra1d3VHMKLS0tIHVsRXFEODZsc2VQSkk5aXBaaEZI
            elROdTRxV3hDeGdFSEtrZjhOamYrTjAKwApWbTQXPwpJoaJSdJdEhrlBbSraERFy
            XA3VnxQBNAFQ/f/STIAJk65NJHic4PdbtdBsNUAgYG1YRFx6PRG2dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:17:49Z"
    mac: ENC[AES256_GCM,data:7bujYVqRvyJ0r5M7dGs9kVA9xtp7YGP6WMMqtJQiOb01zEC2L4VAQkR/AhdqZDUkL3zvLQRCizXgUSESURlDX6UazVzz8V495RXsgC4AOXy2iM0RiDFuJEdvqO6dIHzru5OzsUfNylGZzQYoo13AzBWKqIcAfD/HtTy/17fkq6A=,iv:jWpQN3ap3e/W2UGNJeQi3icWOOiVBunBMv++DUNRJmo=,tag:Lo8XkTnOTBWmHHucPelNPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
