ansible_become_pass: ENC[AES256_GCM,data:i/a1JtfWX+gLCV8w,iv:LKWqqUKUzneuIGuoLd6jacw+7f2MsPjZEehwddr4IF8=,tag:wKZUKkO5Kg7UfdARgjbCJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZUJVSFEvUllvYWpyUkN1
            UkZad2QyaGI0SW4vNm83TjlzNTV0cko4TG00ClY2QnhKZjRzaTBobjQ5V3FjSFRp
            K3FOYUxuZG9KenA5SzZ5aWVDMGJDcFkKLS0tIGs3TWJvTjlkTng1Umo0bFMrMkdN
            VWlZaE9UZnhRQmVocGhYdGpFYWJudVEKyiOFR9vBvq8nE0MD8kxbUZZvDxUh30GZ
            k0wjzj/o2TWC3GTfY7Knw06/QCe/VzYRDViIsHZSxLJcXDNTp52oiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T04:49:26Z"
    mac: ENC[AES256_GCM,data:UaDrRuWN5OLZsynARq8AuVq/YU6OHOUK8NeGqo4pvHR0uqN13007LULmuEuapv6ZgJaS54bwHePvXnzV/ED3hQcNUCZgpwSO8mzeJJYZrHGBzaJAQ9Nkncgrai5+PbF/JRgwp5l76TA+gwl86lJOd5K1fnCFIOBS98AUesARUkE=,iv:ZKviiw/7BwQE/gPukc+cj+0LCLougsql+6QNIIK+JCQ=,tag:M/59JYCd1zZQ/+jyNgue8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
