ansible_become_pass: ENC[AES256_GCM,data:ujWfCUYtUkg+ni96,iv:0gFiMlTFNIFjwPa9TiqjYLll6eIVejYpCCWtv2LvZo8=,tag:NNNMtaq309jDCHR7lguHOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTDd1ZWxHUlhFZjJ2RFRt
            Yk9aTFF4ZXAwZWJpK2tyd1BDYVFxQXBEM2g0CjNqejJCK0w3Q3JYY2gvdENwRzlG
            N1FnWXppWUlUY0JrWFdNc2h6RzFCOFUKLS0tIHVzZkdENDJldjhFSjZic284eXZm
            MVVpeXdWT2pEYWFKTE82dmJ3TWRXKzgK2O9PRkJDhmwa/ttTnb/9nNr4JEc9fJEC
            6HgGB9deDi815Y+q/iJY+CywV93TeYxcdQ21zkwlHieVJKeiQAh4VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:23:30Z"
    mac: ENC[AES256_GCM,data:h06nATKgyFaiVgVv7qsnlpZ1gafVrYMUI78uksNYAvduIXYdkRZFrS7C+G+DJit+L2sGW/b5roaOm7ZXyS8Ap/yKhu+aogilul+6tbeACzXxsfCtjSwN1HLL5zZNURr7UMjnrgxYHYCvGCLdmT58Vii3j1RmYPd5ZyIR/MN1luw=,iv:OrlSQpJxgOHrxYp//uM/mIhWvjQVnUZdZEKJ8LV+30o=,tag:1h7XjTTxL6S3t9EV3qKmDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
