ansible_become_pass: ENC[AES256_GCM,data:tkuTVKMzXZ53im5U,iv:mqbuzQLwqAg5PM16phS7Now7m4l9V1ia9xvAWR7WJ6k=,tag:JQlBCwaLzseOv5hgFENGQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVWp2eXBaMzcxQlZvaHVa
            RXJZcTVId3o3SWVZOFozbzhUd2NhN3NDaW1zCjJDcHFPNHJXRjdpM3Q1Z2JNSXRK
            ZC9OYllGNEhCK2J3djVaZ2xQQjFPUU0KLS0tIHFxMmJjOHU5RXJJL1g0MnJFNFFn
            V2cxRW9hZm50cWdjSkwzMnU3MHA2RXMK5ehPlaIO4js5xqr/6Qk26LF2/Hilff0z
            iNm9gJNGXDXKTpjEHqnb0PUFG2cD1iqUenJ/E1fil1ux4Y1YYSX1Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T16:12:33Z"
    mac: ENC[AES256_GCM,data:Nv3NUr6Oq/74YXYXC7pSSrFv+80SB5oUQXfjKCkUhdcEWhL7jjlhRuFL9ThY0jnh5AuZFiBB6DKFqaVM/5CceLP1inA8gm0sh4MJ//pbk75GHbVtra3G/tB5CWtsJ25/zuDTYh0gN8oemcQOvR6n5+qeKp1sqAwaIPHwgdQRFHM=,iv:6GDpFwE79oxt3MSTs7qv5F9xQNJ9mBUDn/COhYS7B48=,tag:qfMBGOq7wNhUPp5Ua5Xd1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
