---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.204
  share: /volume1/kubernetes
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.6
  share: /volume1/kubernetes
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
