apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:7Q4r7Gu5nq+C0xvy,iv:xeB+n1MRJW+I3fv1/emvlKYnLo9tZTkK88ky1O6jUGs=,tag:sqOJcs9dLnxHMq4J88k79w==,type:str]
    admin-user: ENC[AES256_GCM,data:SX+2rV4=,iv:apYkGv/w5B9foKlAZ/um4o5QY9sGrvLoG/wKCfR5vOc=,tag:SofUSniEq89zDrwfJ9U0/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeEU2M2Nuc0tjNVRETmdo
            LzVjQmpVSzM2ZkIzL1d5UnFENWZKMUZzS1dnCnNvejdpTFQvVHg1OUJZOW51TlRp
            SlprRk9pQzVab1A4V2RtcmZVQ0VnVUUKLS0tIDA2Wno2ckpPYWg1bU5hWkVoWHQ3
            VllLVHNDRUttQzZLV1RWVmtraHFPZFkKafd9OhzStCb2E0wurAYzy3GO4Hprwsk6
            dWZPiO/O7DiyC527CoQVTOD2tQxikirU/Gy6KnGXbKX+YX3wBtVHHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:24:02Z"
    mac: ENC[AES256_GCM,data:TBoQ3dIn+VwBhKdMCMUfZCl1ksR4gTUUNdBr6wzOvzB3xt0Y8CP6Qwh3INilSMHib8ynNYvxUnxD9W5/CroFE9nzTZNe6nrDJi+9P03tJrKZUkNynoPqtkn3wB5Q+W+JgATw1RwTPmoqswF9Z0pMhIMzqSt7181wdC9k407CWL4=,iv:mewK2j6BPHrMufHKmM0LNgRH07ks0wPIEbJicS2Rh4M=,tag:464/PeRgfoq42otyrxSefQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
