---
kubernetes:
  children:
    master:
      hosts:
        k3s-master01:
          ansible_user: drew
          ansible_host: 192.168.1.137
        k3s-master02:
          ansible_user: drew
          ansible_host: 192.168.1.10
        k3s-master03:
          ansible_user: drew
          ansible_host: 192.168.1.140
    worker:
      hosts:
        k3s-worker01:
          ansible_user: drew
          ansible_host: 192.168.1.86
        k3s-worker02:
          ansible_user: drew
          ansible_host: 192.168.1.143
        k3s-worker03:
          ansible_user: drew
          ansible_host: 192.168.1.74
