apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:AQtAg/NBXCXNHgI1lUia/YfvLA5qO9LxPZ0oFE0AZ4Kb5K0ePGx1gA==,iv:n5avWQkhgaso3Tz5a7qQS9a5WwajNHn5Mx36o8oXb/I=,tag:GDuc+CnEjcx+PbgpUlXKdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeXhnUlRjL2Jsc3NPT3pH
            ejFtOWRadVpreTF3NnNUUXkxT2krZEtBQWdvCjQrdDhVT2luWmdGNEpRUUVpTWxN
            cEVuUVR6cmN5THZUZmk1OHd5KytTdGcKLS0tIGNEVmo1c3FTVWdNRUtpdTJsTHli
            SGxnTmwwSmhIbWNHRlJOZC9MbkpZbVEKy5bnBb++N9lyVLOnet8jwUOAkSFL7qfI
            gidA8sf7jefIw/UKQdxTsgN5/oA/i2SPmXsW6Z35aTlZR6KfYZCabw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:23:59Z"
    mac: ENC[AES256_GCM,data:mW2KfTRaxqVffkWzxpfnk0Dgz3PxXvSeXW0dUB5p9scDho6skzZOZ+O0UtrdaseMg/dIZ8sxB5FcBgAxSkuT35Z4eRiKh649DUa2+dCr2deaevnY+4f6r2IiCipLpRUGCKvv/XmcIbdNwXa/1dxQc23jMuTVwkW9bKe1G70XeA8=,iv:Iv/Jzvgh7164TnrbKIn7c6RY5rtyiVJCV1mhc5CIA/I=,tag:1Y6Ri+hPALJXPWVWTqvJFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
