apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:zRqen4tPyQKBJlXbnepg09NBZn+cTDNljXaXQjnL0CYt33s8mQA5KA==,iv:tVZY2zoWY2OyDg/tGlJlqamK9P+yMOsOVVv4JnWuddo=,tag:u2Us7aOng1lmyT/3y3xeyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbFVCUzRTMEsrN1FaQ3Bp
            SjZ0NS9OZzZ0aEJUODNxR0hzS0x4N2xjMVFjCnlTV2hVS1N1ZzZzd2lTd05LQ3Vz
            YWg3aFBMZlgrQlRQQVVSSTFrMnBiN1kKLS0tIEJ1Szl1Wkw5bmlyVi9VRXhibXZF
            QmY4S2ZGT2s0SElSaCtYSHRYakxsT00KM4YDs9Qjf5zwp+nFFAE/1AsNCDmGtPG9
            13NVTeANbRqznhCmQGzCK1bkeZwC1jMdnJ8rdyLcF0UWNqHvvvVOqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T14:26:46Z"
    mac: ENC[AES256_GCM,data:x9MGekbwwhLNEzOPsT7h9RPbo7vGpf9uM4aWvrmEMlsRE//5l9E7WU+m+qdhBexaudA8aVr4QS5vtPKCm7qrnQOqG7d72LO9epvwdAA51lCOifBP9TIuELjerkGZdF+/sDig11GO3RVcSoxLe23CBOD0Kbcfo5gWhYd0MRbBw8s=,iv:o2ayxm6xfuWVs5QDJIOCOQqS5cngj8O+36HcqrShxsA=,tag:RSf0GEBO/QBbOoyChtY0Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
