apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:HM0OAqwUE5d2nozuHbiqFu00UxbYHUjREDo+zNloxuCiNVuack6rOQ==,iv:CF8IK9kbyoaGMqRozluZgPnL+vNWdeRQ2WxYbG5IfRQ=,tag:TygpNVana0WUpEUS0DRvJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSUV4TUFvenhwK0J4MDBD
            b2FzUFM4Z1NDdklEVG1ZMjhQYzJ0M3BKN0VVClNxcWtiSlFyOFZWK2JkbmlpV3Rw
            KzV5Q2xqWnRZSXNRNytSN1FPRXI2UVUKLS0tIEIzeEVaS0FPZlRwcTVDT3pza3FE
            TlVQNW1mMllzdzk3ZVg5Rm11ekN6RVkKESTSeCqT6SqR5F5amDqpZCZiuU87JFNl
            SkKEo4p3rllehA4RGvEI/+DV0x4v53a2cPGvQfwu1H8IXc0iP4GUAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:18:18Z"
    mac: ENC[AES256_GCM,data:sHg2gmvNZFfvZaqeJnJQwCmsQJV14Bon+ScwAGwWuBety+U2IJjCZtv/fI5Wxk3gSD7SsuKUty7zVB2RM/iC4VzNHmpBydzP8qJRRyv4WZLKXCj657TB1Sio+HYzgYPz00BFq49bBKod1DL1dLGOAY/TWy0SjdMWrd+vVJoAN6s=,iv:cxjhIjQvzuueH7Z7PXz8mbBdKYoLdugblvyT8gUah5w=,tag:1JkxoeyRQ3GsZSUZX/9dRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
