apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:7OiMTs84i2Nng1YD7QnCU57SG/Ax9DDcia6Hm7bkxWMxNOWAvTDD4Q==,iv:SArebahLbkzb1mwFDsOGrCmuLCTMh6KxF1+izR4z1u0=,tag:ozOvvrGGr2tkZ+WQxRHmSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bUZCbVppK1Q4TXBuZHZo
            TWF0RGhlckl0TEh5WmlZR1l3UG9VOVpQQzNjClcxZjFDRFdjcE9BMEZmUUM5U280
            UlkrR0VVYUU5dUxiVkJTdFVSRGUzYWMKLS0tIHlpV2JWWXJhY01oZ3pNcHRaL01q
            ZTJCNVNraXFZS2xwUlp1a0VXaStWb28KKgBOYLFarKGRkFyrw3XKQ+uAzNwyH1hT
            eA9mv/SJJFJJF8GdXvg61O8bfBANwg5o0kZf0hEXl0DRWp4W9IugdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T16:13:02Z"
    mac: ENC[AES256_GCM,data:n92RoX2qcz9HoRA9CqAf1zfAeTMSCbxXTH9aaEyvH8k3rmxQk+TbJuofizagQS3bT7qYTNOdiMcxiFza2VnHWhnYzRqnIRRtbQvQ4XfhAxlZ9efpAqJh2nBd7EyAfrkrj+Ir+fmcRBb4f+TCPst1Z0Wz6ACWLDHITH4ZZRNJhwg=,iv:2lJE5KNQSdcT7dMQWNwK3WZkaTKiE5FaGxHhaAdM30A=,tag:mMuMLcTHOlgN3uRNVQyphg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
