apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Fec0IqSrK9PM5Hj9nOZCuhLiHrMEnaLeVdWepJYVM2VI0/zwDtSG6Q==,iv:CGq9d8pMTjKrM9nUJx7p5DhPGiaodLzeGJ9uCL9J+Dw=,tag:vZB3OllQEaxNgaloBSeALQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RVJYekE4YisxZ0F1bHJh
            T2dXSEcxbUxDYTEwMW5iTmFGMC9rbWdpbnc4CndkRmVkcUtZQWhDcHMrOHRNa2Jq
            WDdiVkxhYWc0OS9aK293UHhCZnh1K1UKLS0tIG1YOUhJbnh3RmpUT2JEaHQwVTF5
            VHFGUFN6ZklTdUx6WjZjNTROZlFjNTAK+P5pjbagjLhzwMOTvAFXutlLUy2UZnRu
            LW0xhbMyT/aKLk0clL9ZQHQ3UYnthTvpI3lcRXs3lFSByWhLYtabsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T05:32:41Z"
    mac: ENC[AES256_GCM,data:e9p+WCm6gzIv28aJx+D0Qmos5/4wAuwbQ23YU0Tdava42Y+NeIJI6Xlkf7tVGNGp3DvfBqyXh3+Dv8WkaOG9dHfFB+gLpq3Pda0+INGvfAWS62s6JfnFi2FiwCmMeFOBI40AGJzljxjXs6SCZj7lFaGTQoRGqUveiZd4jnvrfwI=,iv:ps53zN6yJxgUMszm/VcriMKEonD1khWO4E01lgrcbd8=,tag:yd+aUg7WRT2elpQeXPH6KQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
