apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:k75DQR1HFpZaaA55B2SpjR7a/0GPK5cK7MYpghoMfnMMSlfdaWM6gQ==,iv:N2o46RhQglJG4hDbnQq83NaM3eidwemsuGy0ZMDuH1M=,tag:eODesFeBqYVsKHbv82Tm2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYmN3c0NWd3JBS3A3WnR5
            RktEK296U0VEaHFYejM1bGxrTi9wcHhaaG1JCi9adzBGVlBsODFMQmlEQmFmS2RN
            Sys4cm12MkJiWUoxTG1veklGalNyRFEKLS0tIDRjZHlQdmVPVzZSN3JyazZJQ0Zq
            ZEczbnVHT1BIRGpocHpXMkVPS0I3OUEKT95NB3HtjIZhJ/ZQKbbgxrwAlGILEJrT
            W7TdNea35lrZ5pTMFKSVQ5fkwlXDAQif4ccpmmowUSCypltKDfrKww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:32:55Z"
    mac: ENC[AES256_GCM,data:DPAnCSQk0QrWDxDnmRla3O8NOUk9kCO5MR00VyvOUFZF5yH4Kyx3LEq6XJePgjhg7OzW5e+Z4Xp/CEGAZuQJEcuuIEasCvR4ZHDTqqE6JgGaFV05cVW20OXXifNcqOG5xeXNPTJNl2wiAMQaLrT9SVkq38q9+XbOM6qN1mqQOZI=,iv:SUK5fC9ahb0mJ1HYQg8QBkwP1DOIw7+zgfX07+OT3YE=,tag:puLBtWG6nln6TgGbheK5Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
