---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor-system
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    externalURL: harbor.drewk.org
    expose:
     type: ingress
     tls:
       enabled: true
       certSource: none
     ingress:
       hosts:
         core: harbor.drewk.org
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          storageClass: hdd
          size: 100Gi
