apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:ZmwO+qqaC/Mu9ZYjPCMCTyk3xZvu4goN9pLMVtz2cvBFa+aJ5+rJ/gVHlpDigMgySFFI9Pz2Nt/u9HiA,iv:4RE9FcKRARKaXnSV2hOlWxuolSHz7IZYHgEY20Jgc4k=,tag:N8I+SZhBn1bOvjBB4x19Yw==,type:str]
    username: ENC[AES256_GCM,data:IMDY1uk=,iv:d/OlsGLmpJ5aFo6Z1G8qQuMRs/3W/MNc8sPW/ZZrOu4=,tag:JzK/zD3bXcUpRKE++H5Xuw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MFhMcUpiZUlMSW50NTNk
            L1VBSlVsM0l5UU9Ba2JrOUR1cmdOVmlaenhRCndCdVllRHo4RTJ3ZE4vRzExa0E3
            djFyTWVHdml1dTU5MUpwWWVKaVE0YWsKLS0tIElhd2lNcDU0ZmFmYVhndGIxQXcr
            eTZlQkw2dTNCUlRqSytvR3EyQkp5WTgK96hHaq2dKNXnQnYu3YZMbXFYvZsv+GDL
            iIPMXGs1HcfPIYG9mU2nefBcYlnEoP5wM8I+bH+PGH1SdQnAvGA61A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-15T01:07:44Z"
    mac: ENC[AES256_GCM,data:a9loU3ju7TXphAqAsAjLZIWsyhw8XACfvxctKNGPIEq+D8oi8evqKfEzrPsmwlKQlp46NIMC7Hy0QK2E2BGRril5gKaUjbql1jVjZF983kjoGXdzWe65ORsH46aus7ViJ6RzeBVUMy1icGZk4B6QCT5hpXV7puNRbdMSUmUwYC4=,iv:g+amafpqXvrXihX3R/0JVN6c+t8pN7+6whXtUZsjNDg=,tag:zXhCQftqMqhNR5LD/1H8GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
