apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:6BT5Cm+CMjSftcIm9nQE65s3bfkQAaGC/TGQLU7ws5d2aTbEAgFungaNgkp2BP7i0P9G1gYy6+gqXJGf,iv:kxDAhxupUNQRcoGTmggV2E/GDVU2pPaD7JtnaAPHCo8=,tag:v+JOQmW7Ca2nvmmoH56wlA==,type:str]
    username: ENC[AES256_GCM,data:ddgFlIA=,iv:MYywar0o77cv089Ez9ui2aFkAs5dqTxF2MoNcHY5Q0s=,tag:bW4N5PRulGZCDj9CJod7MQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NHdrTi9BUlZrL0c0RFFB
            dDlMZlZybGIxVnlBcldjbWdLZlNHYnRWTFc0CndFQUU1RWpkK3p2Z2VpOFJiVXBE
            bU1ndVlmY3VDOUQ4SFNTZXc5TTFIVVUKLS0tIGR5UWIwMUlMUUVlZ25reGNEc2Ny
            QTFiYjVTaGxDS0lERm8xNm1WZzZBWDQKEGRuTFgbEWnlz6/blYp/nDVLN8HmGC6r
            VBMahiebJJM5EwLHIC/B0CggGHNjv7dqeoqiI5kAXAjfkOrmqkyw8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:36:24Z"
    mac: ENC[AES256_GCM,data:icpJazVnbkQJ2Q8+kdg34EYJSxM8/ruhoDzYFbJoFCAJkJ6eQU/Xh18v0D8cTdWUVh8ldggXc1EMAFIdAgFZq30ZWrJB2HLciZxdHMxFj6AOpg2L2v4CjLCFz6lzjc6JGsB2x1y8hpHsnGY6ZS5mBJ5wvYxteCkPKAI6yCFnPSk=,iv:1r0sRgIU5Dw2JWvO0iyBx3DuiHg1Ol+px0EkORuEUis=,tag:eopVNMYiLWRFfXZo1hk7uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
