apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:KrV1Ea0rRRc8fsz/1K5UYE99EiJRG+tJ,iv:mOMvXxkcQmnfVZEm0Tp1nXFEFgQhX5vwJ/3oFZLeq3k=,tag:S/LnZvsTlinz2dH6TunpDA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bB+5JnU8CaUGL9eLYVsnByjFAtZ8u6uHcci3u702h2kbG738,iv:61LvDUe2jlpfgi6Sii078bjswk67d9wSJdeKsi+LpC8=,tag:ZjsboG6m1GS/TFhOit3Whw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:5Wg9T0KYzQQn,iv:tHWdAI6YYg4rKnuzlnJiU4BRZK4dvgrsvZn0tLafM1A=,tag:/KMxtQMVg4LYijWNFPSNAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOUdOQXpDMDFnV0EzU3JP
            Q0MwZzlxUVJhd3NrSFh3bXR2S0VwWS9DeEFJClBjTDFYZDY4STZwdTRtZkNkQkJK
            dmE3cjFKQi80QWVGVEN1QlhCa3hvUU0KLS0tIHZaOFUrd0hZTWtEckhkcWZWcGFC
            S1UrQllISldDYUp1NGNCNGZSMXRhUk0K7bXXJGPueqjnow06A+9FaZTI/Quz5Qjr
            ZZj4vHKDz9utyASySlJu1Fs1CBUVTAv1Iy+AqGl9dz+ivta40/TlJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:23:58Z"
    mac: ENC[AES256_GCM,data:pex3+scqqSeTK9mOSaEIWyFNLskd57EgqidEqGOpJMxBJ5iyoF/wEsTZQY+bBv1tYsaZiygpQAAfIttZ6jSSU2VqG9Fxdv7P3SXUbC4Ao6zW3txH0nwA88h8qc/I4Bc30qO+3ZB5zIqfDNnSbA8noRfoaopxa/cs/UZHgTmrpDk=,iv:xJrplnHWrbv5Gq4DR+y1FGr2bObPXMIjgP1Tdps7IGI=,tag:oWmCnf98j3rhaYinzmTeLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
