apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QeX3p/TeWaDHucfh2JkVbr8nTdjwpFq2,iv:BqDhk52fHRpjag6kLfAEF773CzuJC0hpgozxhsQbr9E=,tag:A9pYiFwpV5btJhwtFI0QUA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ELjhKWYxz74Pyx8GvnTZR9JJLh2irWnptD04DLDBC2Cl/kPb,iv:7lO+ISBC2CSZdJl5Kylt1Pv8zHr6XFhlEPS+d4FCTQc=,tag:U07HZwz+PC4dl5deG2QMsQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:XN4lvfeL1yNx,iv:iLZpysWUqJ3DSW1F7JhfN2C5qgt9+hSL6OY9fuuR5Cs=,tag:lfZ8F2n/5S2PqHmW0mLJ7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNjAyUExXMFBVRGlycWxt
            dTdDU0JPUUJSZU9EVVFkeFJ0TmhlaGNBdlhVCjErYkEvTTU0Y3FhY2NuZGFJZ3Y1
            SEpBbVhqZFROOVVyaEdzVjkvS0IvTWsKLS0tIDAzaklwVlFvZm5NT29LTzVxZ1JM
            L0t4V0xRQlUzRUw1SHllYnhiMWQyK1kKnYQPZB27df4UyiT4V0nJcuyOklkN5DqO
            lZey0aw1f676R1/X2/TsTOQsG6SU7SI3YaKkMIl0ryAbFmkaeZj+LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T14:36:09Z"
    mac: ENC[AES256_GCM,data:JCRsQl6tGtdUsqGuVXMs7CUHJuxwlxCqE0lmJH0ycm8Ttfj9tduz3PoznYO6kgFwsbbks8dY1SIxL1keXYDp6qGuDGv4AmbIw4g9Pnrh4XupbTNd/jqUTEmaTF/AScBcr01uBWL0XqtMXyTbzwbfpKsqxub4B20bTLZXkSifobY=,iv:yIk+i++9TtDrYCt+wVAH7dyv2Bcw73tP+aypnZUqu4Y=,tag:2nojSB+2m4c3/6XGcTIGtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
