apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:JKOK3gr1lhgSiPoCpYcnFwlRswx/Pz4/,iv:dePmyraz7QG+EZpbLSEKCgIX3tRMm3yfk2lCoAMgUSw=,tag:G+Z7S+BtizcBJ/jZpuAE2Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rek/8hOU5vQHvR9/GAggo1U/ZqqZfxhCIN8XlqmRneEkuKDU,iv:Qx8LNuGWTjGiOtK/iu6ngSQN8dRrEZBZ6JRr06BNFyI=,tag:jWPFV+4k2n9tX3JpB3CNpQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:JcicwWgZgiTc,iv:oPfsd2rGsKX6qAIX0abcyQoVXwHT502QsDejVVqyhuU=,tag:isDBtGZqfMwol+N6MyGUbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdGZnZ01icFcwVFFyMC9z
            MmFtV0N5VlprVHo0SFp1Uks0L2Y4NE5idkZnCnorSFFoaHNzS2dySUFJTFNnWHVz
            eGJUMmdTK296V0VISXluQ2p2cmpwSmsKLS0tIHFuMTJDcmtHSFRKdVB3ZWQxcnZ3
            N2pFVGpmYk5vR0pPL1VTMlEvenZzdUUKylz5jByqGM4EmY+6lvjCLoWb+u8efeV9
            Fv9eoAPr7lZLd5ElYBT8wNOQ+Z3LybuWF8hGL/11yWjDl4sohGy9LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T05:32:40Z"
    mac: ENC[AES256_GCM,data:zRjyu2GC9iemw2cnoYe2TQtfxidrOSPk2Xb6bCbxBkBm5+LzHcpJYTX0xNhMdVJkA0yhFjXbhfn3Ur2MnpkVWveQLR27Q09xspVRvehEXUklou7Oq3Eyfy0J67O8UoIjY/gBpIEBZClR88F4SKOVxoGzdGnOWk3JPIiasX0XUjI=,iv:I28T7rw/ruYndyK+asNxIWLcFKhbW528xOHl9FZZmmA=,tag:S5ojAGNMnmWmEPowI/9L/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
