apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:KAAZTSnWn77prAAvhCp8yJnX14RvdMoA,iv:DKQZS5/e8Nq9eKefkreNILAB9BfFkYM85xjb4Qn1AJ8=,tag:C9Sh5UJBMGgyPyV7Rp+f0Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:m7E49k2spCZwg/ljWz7sRGx03a2fGIN+OQPNzQByZElNcbNj,iv:b9wBUn8eX8zHwxDEBcWVcB1o0AAW9veSydsgr0brqAc=,tag:XaWRqGkZPxAahEFnxdK3tw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:58jsHsYMh4Yu,iv:P8dDzZRhsBmhOIlqrI3oxmKOBa/MX5fG5NCccSg5oM8=,tag:R+p9kZEDqpIaisnPjQCwgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ1cxWitHWUxBVkxxYm00
            K1JmaUptQUlYVXZvZHRsTU5GMlQyeFdlM2xFClZEWVpSVHREQ2NOYk05VUVyYVRX
            UVJlMW9uTi9RZWR1ek54SnhTVXRwL2sKLS0tIDZPdnRuMnJJWkh6UFl5MEpUczlG
            YzVLb3JZU3N5TGMyMmNwemNlUXdTcEEKFiHlAy3snVi75piO+IuUhbcei6mpBKbM
            8ctxV6ZgyIF9kTqvai2d3OtvMi9MCNLtisfy8s4lD+fE6blpOjEjYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T04:49:55Z"
    mac: ENC[AES256_GCM,data:AW3mEebymO/I51VNDntnck/qtyUf6aqvlc5Y9g5Sg48vQADuCVnodOwOYCn6KRe4Qckmk8iIuZa5iBAZI7wYVpNCLeMv21avDUU/Mt7lrPbEM0Lxa8nwb6FcUAdAvPxZC+ImABiiUeeyEQRzxNyCQrQzbxpiEoVS727/ZvG2Oak=,iv:Gg5oYkGmllofz31zXjjrKJXKbdUxjEWiz8gj2UFIucA=,tag:6YgVtVAAKAwDZ6lf938Qqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
