apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:U4jLHG02V+PzAl3SalbPAN/aZxlcK8+0n+YV1iV+1Gh4+oAI,iv:XuSJdSZJ32WULgOgQjdzaLXs6uTL8b8cSgkYbIjZGZo=,tag:8RXGCrg7RvZKdOXb4s+OaA==,type:str]
    credentials.json: ENC[AES256_GCM,data:HJQgMCE1Q6uhgIJ/begS4Fa6RhzIbNZ+nWyYdbWSYh9/e3wx0ZewcPgVCUqsDZ97ahc/cYwxJY1q0MXK4LQEljBap2ykSvwFHc+9BaoiZl6nXUzK55kY4+uIRjq0anfOrCbRm5zM3j9isWMxmOnhlMEIBKwEVh+d3K49dIZAZ5Czh/sywrxpXKu1xIme2/UMWbfCsi/uI/+3AMm+KHH5IP2Ss1mEuF+P/h3vv5Hh9g==,iv:PdQlUcE0Pz6yFOmg6yU/f2NnZFheupkkyNFHumfF/5M=,tag:TTMynYHkIwS2qVnZAX2zRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yuh6vyga3ffwfa7v45getw5044kqzccu558g2jv4jqfm09tf2yzq90snqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ1ZhWjJhc003RkpDVzJ2
            NVo5ZE5NcEREeUlJVmxsWHZvM2xaSjFBRlE0CktiOUFldEJzOUJMWEh4Qk10VCtw
            MlFuYnJLdGpQbVV0UUJZQmpPdUpoNU0KLS0tIGkwb1hIRG5FZlR1QzE1aEVNTGti
            NzhXUU5iUFVTNDk3dnZEcEdlRm5WeUkKImiexldt04eSmQlrrqS8NNFjl/2YB5Ix
            18JELF9F1F2bTlN23mkzztJ6cOI1pWWfwCpR3MxcCwrpGWDlJfwzJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T15:23:58Z"
    mac: ENC[AES256_GCM,data:CgMthSlZQuQRLpsmD33mZehoYfYCGKuRS/u9uklKbbd6r2kdrJXnwGbAaxvPHJPLDqyK3cpyFAJBr9hWtoBMBK3fZh5xM74T9p/df9fZWo2YTuL5WDg6F4dHmnWRA12RuzMhkFftV/jk29aV3a+4Szd0QLXKkqPFP98NsWfl+pY=,iv:y9kG2kRFhc0b3V+gF7FZVB3kxtzOJDi4qxI/jHwu/1M=,tag:zv40SlOLruFGqi1QDAiY6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
